import type { NewsArticle } from "./types";

// Evergreen "10 most important space stories of all time" — used only when
// the live API is unreachable AND no cache exists. Always relevant.
export const FALLBACK_ARTICLES: NewsArticle[] = [
  {
    id: "fb-apollo-11",
    title: "Apollo 11: One Small Step for Man",
    summary: "On July 20, 1969, Neil Armstrong and Buzz Aldrin became the first humans to walk on another world. The mission fulfilled President Kennedy's challenge and remains humanity's most ambitious technological achievement.",
    url: "https://www.nasa.gov/mission/apollo-11/",
    imageUrl: "https://images-assets.nasa.gov/image/as11-40-5874/as11-40-5874~medium.jpg",
    newsSite: "NASA",
    publishedAt: "1969-07-20T20:17:00Z",
    publishedDate: new Date("1969-07-20T20:17:00Z"),
    featured: true,
  },
  {
    id: "fb-hubble",
    title: "Hubble Space Telescope Launched",
    summary: "Launched in April 1990, the Hubble Space Telescope revolutionized our view of the universe. Its iconic images of the Pillars of Creation, deep fields, and distant galaxies reshaped both science and popular imagination.",
    url: "https://hubblesite.org/",
    imageUrl: "https://hubblesite.org/files/live/sites/hubblesite/files/home/_images/STScI-01EVT5DEMSJF67XBSF4WAQ51T0.png",
    newsSite: "Hubble",
    publishedAt: "1990-04-24T12:33:51Z",
    publishedDate: new Date("1990-04-24T12:33:51Z"),
    featured: true,
  },
  {
    id: "fb-voyager",
    title: "Voyager 1 Enters Interstellar Space",
    summary: "Launched in 1977, Voyager 1 became the first human-made object to cross into interstellar space in August 2012. Carrying the Golden Record, it now drifts among the stars as humanity's farthest emissary.",
    url: "https://voyager.jpl.nasa.gov/",
    imageUrl: "https://voyager.jpl.nasa.gov/assets/images/galleries/voyager/Voyager_-_high_res.jpg",
    newsSite: "JPL",
    publishedAt: "2013-09-12T00:00:00Z",
    publishedDate: new Date("2013-09-12T00:00:00Z"),
    featured: false,
  },
  {
    id: "fb-eht",
    title: "First Image of a Black Hole",
    summary: "In April 2019, the Event Horizon Telescope collaboration unveiled the first direct image of a black hole — the supermassive monster at the heart of galaxy M87. A glowing orange ring of doom, exactly as Einstein predicted.",
    url: "https://eventhorizontelescope.org/",
    imageUrl: "https://eventhorizontelescope.org/files/eht/files/20190410-78m-800x466.png",
    newsSite: "EHT",
    publishedAt: "2019-04-10T13:00:00Z",
    publishedDate: new Date("2019-04-10T13:00:00Z"),
    featured: true,
  },
  {
    id: "fb-jwst",
    title: "James Webb Reveals the Universe in Unprecedented Detail",
    summary: "Launched Christmas Day 2021 and now operating one million miles from Earth, the James Webb Space Telescope is showing us galaxies as they were just 300 million years after the Big Bang.",
    url: "https://webb.nasa.gov/",
    imageUrl: "https://www.nasa.gov/wp-content/uploads/2022/07/main_image_deep_field_smacs0723-5mb.jpg",
    newsSite: "Webb",
    publishedAt: "2022-07-12T14:30:00Z",
    publishedDate: new Date("2022-07-12T14:30:00Z"),
    featured: true,
  },
  {
    id: "fb-trappist",
    title: "TRAPPIST-1: Seven Earth-Sized Worlds Around One Star",
    summary: "In 2017, astronomers announced the discovery of seven roughly Earth-sized planets orbiting an ultra-cool dwarf star just 40 light-years away. Three sit in the habitable zone where liquid water could exist.",
    url: "https://exoplanets.nasa.gov/trappist1/",
    imageUrl: "https://exoplanets.nasa.gov/system/resources/detail_files/2160_PIA22093.jpg",
    newsSite: "NASA",
    publishedAt: "2017-02-22T18:00:00Z",
    publishedDate: new Date("2017-02-22T18:00:00Z"),
    featured: false,
  },
  {
    id: "fb-51peg",
    title: "First Exoplanet Around a Sun-Like Star Discovered",
    summary: "In 1995, Michel Mayor and Didier Queloz detected 51 Pegasi b — a Jupiter-mass world orbiting its star in just 4 days. The discovery, which won the 2019 Nobel Prize in Physics, opened the era of exoplanet science.",
    url: "https://exoplanets.nasa.gov/exoplanet-catalog/4290/51-pegasi-b/",
    imageUrl: "https://exoplanets.nasa.gov/system/resources/detail_files/279_PIA19827.jpg",
    newsSite: "NASA",
    publishedAt: "1995-10-06T00:00:00Z",
    publishedDate: new Date("1995-10-06T00:00:00Z"),
    featured: false,
  },
  {
    id: "fb-mars-water",
    title: "Evidence of Liquid Water on Ancient Mars",
    summary: "Rovers and orbiters have built an overwhelming case that Mars was once a wet world. Curiosity, Perseverance and the Mars Reconnaissance Orbiter have all found mineral and geological evidence of long-lived ancient lakes and rivers.",
    url: "https://mars.nasa.gov/news/",
    imageUrl: "https://mars.nasa.gov/system/news_items/main_images/8901_PIA24484-web.jpg",
    newsSite: "JPL",
    publishedAt: "2015-09-28T16:00:00Z",
    publishedDate: new Date("2015-09-28T16:00:00Z"),
    featured: false,
  },
  {
    id: "fb-pluto",
    title: "New Horizons Reveals Pluto's Heart",
    summary: "In July 2015, after a nine-year journey, NASA's New Horizons probe became the first spacecraft to visit Pluto. It returned images of an active, geologically complex world with a giant nitrogen ice plain shaped like a heart.",
    url: "https://www.nasa.gov/mission/new-horizons/",
    imageUrl: "https://www.nasa.gov/wp-content/uploads/2015/07/pluto_color_mountains_plains.jpg",
    newsSite: "NASA",
    publishedAt: "2015-07-14T11:49:00Z",
    publishedDate: new Date("2015-07-14T11:49:00Z"),
    featured: false,
  },
  {
    id: "fb-falcon-heavy",
    title: "Starman: Falcon Heavy's Maiden Voyage",
    summary: "On February 6, 2018, SpaceX launched Falcon Heavy on its first flight and sent a cherry-red Tesla Roadster — with a mannequin named Starman at the wheel — on a billion-year solar orbit past Mars. The two side boosters landed simultaneously.",
    url: "https://www.spacex.com/vehicles/falcon-heavy/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Elon_Musk%27s_Tesla_Roadster_%2840110304192%29.jpg/1280px-Elon_Musk%27s_Tesla_Roadster_%2840110304192%29.jpg",
    newsSite: "SpaceX",
    publishedAt: "2018-02-06T20:45:00Z",
    publishedDate: new Date("2018-02-06T20:45:00Z"),
    featured: false,
  },
];
